# 1. Create a 1D array of numbers from 0 to 9

In [4]:
import numpy as np
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print (array[0:10])

[0 1 2 3 4 5 6 7 8 9]


# 2. Create a 3×3 NumPy array of all Boolean value Trues

In [12]:
# A boolean array can be created manually by using dtype=bool when creating the array. Values other than 0, None, False or empty strings are considered True.
import numpy as np
bool_arr = np.array([1, 0.5, True, True, 'a', True, True, True, True], dtype=bool)
bool_arr2 = bool_arr.reshape(3,3)
print(bool_arr2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# 3. Extract all odd numbers from array of 1-10

In [15]:
import numpy as np
array = np.arange(1,10,2)
print (array)

[1 3 5 7 9]


# 4. Replace all odd numbers in an array of 1-10 with the value -1

In [17]:
import numpy as np
array = np.arange(1,10,1)
odd_values = (array%2 == 1) 
array[odd_values] = -1 
print (array)
    

[-1  2 -1  4 -1  6 -1  8 -1]


# 5. Convert a 1D array to a 2D array with 2 rows

In [22]:
import numpy as np
array1 = np.arange(1,11)
print (array1)
array2 = array1.reshape(2,5)
print (array2)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals

In [25]:
a = np.arange (1,10).reshape (3,3) 
b = np.arange (10,19).reshape (3,3) 
c = np.dot(a, b)
sum = np.sum(c)
print(sum)

1944
